openapi: 3.0.1
info:
  title: Coodesh challenge
  description: CRUD(RUD) Products
  version: "0.1"
servers:
  - url: http://localhost:8081/api
paths:
  /products:
    get:
      summary: Retrieve a list of products
      parameters:
        - name: code
          in: query
          description: Filter products by code
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter products by status
          required: false
          schema:
            type: string
        - name: imported_t
          in: query
          description: Filter products by imported date
          required: false
          schema:
            type: string
            format: date-time
        - name: url
          in: query
          description: Filter products by URL
          required: false
          schema:
            type: string
            format: uri
        - name: creator
          in: query
          description: Filter products by creator
          required: false
          schema:
            type: string
        - name: created_t
          in: query
          description: Filter products by creation date
          required: false
          schema:
            type: string
            format: date-time
        - name: last_modified_t
          in: query
          description: Filter products by last modified date
          required: false
          schema:
            type: string
            format: date-time
        - name: product_name
          in: query
          description: Filter products by product name
          required: false
          schema:
            type: string
        - name: quantity
          in: query
          description: Filter products by quantity
          required: false
          schema:
            type: string
        - name: brands
          in: query
          description: Filter products by brands
          required: false
          schema:
            type: string
        - name: categories
          in: query
          description: Filter products by categories
          required: false
          schema:
            type: string
        - name: labels
          in: query
          description: Filter products by labels
          required: false
          schema:
            type: string
        - name: cities
          in: query
          description: Filter products by cities
          required: false
          schema:
            type: string
        - name: purchase_places
          in: query
          description: Filter products by purchase places
          required: false
          schema:
            type: string
        - name: stores
          in: query
          description: Filter products by stores
          required: false
          schema:
            type: string
        - name: ingredients_text
          in: query
          description: Filter products by ingredients text
          required: false
          schema:
            type: string
        - name: traces
          in: query
          description: Filter products by traces
          required: false
          schema:
            type: string
        - name: serving_size
          in: query
          description: Filter products by serving size
          required: false
          schema:
            type: string
        - name: serving_quantity
          in: query
          description: Filter products by serving quantity
          required: false
          schema:
            type: integer
        - name: nutriscore_score
          in: query
          description: Filter products by Nutri-Score score
          required: false
          schema:
            type: integer
        - name: nutriscore_grade
          in: query
          description: Filter products by Nutri-Score grade
          required: false
          schema:
            type: string
        - name: main_category
          in: query
          description: Filter products by main category
          required: false
          schema:
            type: string
        - name: image_url
          in: query
          description: Filter products by image URL
          required: false
          schema:
            type: string
            format: uri
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of products
                  page:
                    type: integer
                    description: Current page number
                  page_size:
                    type: integer
                    description: Number of items per page
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
  /products/{code}:
    get:
      summary: Retrieve a single product by CODE
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
    put:
      summary: Update a product by CODE
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
    delete:
      summary: Delete a product by CODE
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product deleted
        "404":
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        status:
          type: string
        imported_t:
          type: string
          format: date-time
        url:
          type: string
          format: uri
        creator:
          type: string
        created_t:
          type: string
          format: date-time
        last_modified_t:
          type: string
          format: date-time
        product_name:
          type: string
        quantity:
          type: string
        brands:
          type: string
        categories:
          type: string
        labels:
          type: string
        cities:
          type: string
        purchase_places:
          type: string
        stores:
          type: string
        ingredients_text:
          type: string
        traces:
          type: string
        serving_size:
          type: string
        serving_quantity:
          type: integer
        nutriscore_score:
          type: integer
        nutriscore_grade:
          type: string
        main_category:
          type: string
        image_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
